### PR TITLE
Hai stations review

### PR DESCRIPTION
**Pull request by Amazinite**
I get that the system editor is out of date, but come on. A lot of these were really obvious. :)

I've removed five of the mothballed stations while seeking to avoid objects overlapping. If you want to readd them, I'd suggest placing some in Unfettered space. And make sure to check the orbits if you do.

### CODE REVIEW

**Comment by MasterOfGrey** [comment]
Yes well, this _was_ originally meant to complement the expanded systems that Fero was working on, but for whatever reason that never got around to being PR'd... (but I didn't check overlap avoidances for that reason).

I'll double check these in an hour or two. Some of the stations with descriptions were in specific places for reasons, so I'll just check through those and make record of what's been moved/changed for future reference. Then should be all good.

**Comment by Amazinite** [comment]
Well if ever you're depending on another PR being merged, you should say as much in the PR description and keep the PR as a draft until the PR you're dependent on is merged. Either that, or just have a version that doesn't require another PR and a version that does so that the merge order doesn't matter. But if you're PR doesn't *really* need another PR to work (in this case, you don't *need* increased system sizes in order to add more objects to a system) then you really shouldn't be holding a PR hostage until another PR is merged.

**Comment by MasterOfGrey** [comment]
Yeah no, I'm not holding it hostage, I'm just saying I think that was why I had overlooked that stuff at the time (expecting the other one to be imminent), and then just... forgot.

**Comment by Amazinite** [comment]
It looks like only one station referenced its location in a manner that didn't match anymore. Should be good with the slight wording change I made. Also patched up some grammatical errors I found.

If everything here looks good to you, then the only other [comment](https://github.com/endless-sky/endless-sky/pull/5670#discussion_r726616196) I have is on the description of Greenview seeming to reference the player having a spacesuit equipped, implying that the player wears said suit while in flight, but the Void Sprite missions where the player is described as equipping a suit to leave the ship would seemingly contradict that, so I think the start of that description should be reworked.

**Comment by MasterOfGrey** [comment]
So for clarity we've nuked Coppermist, Indigosprint, Icemeet, Silverleap & Lightstead got nuked and moved to Thornlight. 

I can live with that, and I've taken a backup in case I want to dig them back up if/when expanded systems become a thing.

**Pull request merged**
